#!/bin/bash

echo "Building Pulsar AngularJS Front End"
grunt build

# Patch in the shit I just don't manage with Grunt (prototype stuff)
cd dist
	cp -R ../app/source .
	cp -R ../app/scripts/sandbox ./scripts
	cd ..
