#!/bin/bash

export SUBDOMAIN="rjc-pulsar-api"
export NODE_ENV="development"

export PULSAR_API_BIND_ADDRESS="0.0.0.0"
export PULSAR_API_BIND_PORT=8080

export PULSAR_ALLOW_ORIGIN="http://127.0.0.1:9000"

export PULSAR_API_DB="mongodb://localhost/pulsar-api-development"
export PULSAR_GMAIL_USERNAME="[CREATE ONE]"
export PULSAR_GMAIL_PASSWORD="[CREATE ONE]"
export PULSAR_PASSWORD_HASH="[CREATE ONE]"

grunt
