#!/bin/bash

export SUBDOMAIN="rjc-pulsar-api"
export NODE_ENV="development"

export PULSAR_API_DB="mongodb://localhost/pulsar-api-development"

export PULSAR_API_BIND_ADDRESS="0.0.0.0"
export PULSAR_API_BIND_PORT=8080

export PULSAR_ALLOW_ORIGIN="http://localhost:8080"

export PULSAR_GMAIL_USERNAME="[CREATE ONE FOR PULSAR]"
export PULSAR_GMAIL_PASSWORD="[CREATE ONE FOR PULSAR]"
export PULSAR_PASSWORD_HASH="[CREATE A UUID/GUID AND USE IT HERE]"

node .
